"use client";
import { useCallback, useEffect, useState } from "react";
import { Folder, FolderLock, Users, Plus, LockKeyhole, ArrowUpRight, FileText, Link2, ShieldCheck, Loader2, Globe2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Empty, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { toast } from "sonner";
import { api, post, Session } from "@/lib/client-api";
import { FileHub } from "./file-hub";
import { FileActions } from "./file-actions";
type FolderInfo = { id: string; name: string; access: string; group_id: string | null; protected: boolean; owner: boolean; locked?: boolean };
type GroupInfo = { id: string; name: string; member_count?: number; invite?: string; owner_id?: string };
type DocInfo = { id: string; name: string; updated_at: number };
function SignIn({ path }: { path: string }) { return <div className="signin-notice"><LockKeyhole size={20} /><div><strong>Seu espaço começa com uma conta.</strong><p>Entre com ChatGPT para criar pastas, participar de grupos e editar documentos.</p></div><Button asChild className="primary-button"><a target="_top" href={`/signin-with-chatgpt?return_to=${encodeURIComponent(path)}`}>Entrar</a></Button></div>; }
function FolderGrid({ folders }: { folders: FolderInfo[] }) { return <div className="resource-grid">{folders.map(f => <a className="resource-card" href={`/pastas/${f.id}`} key={f.id}><span className="resource-icon">{f.protected ? <FolderLock /> : <Folder />}</span><strong>{f.name}</strong><span className="resource-meta">{f.access === "public" ? "Pública" : f.access === "group" ? "Do grupo" : "Privada"}{f.protected && " · Com senha"}{f.owner && " · Sua pasta"}</span><ArrowUpRight className="resource-arrow" size={19} /></a>)}</div>; }
export function Library({ view = "folders", groupId }: { view?: "folders" | "groups"; groupId?: string }) {
  const [session, setSession] = useState<Session | null>(null), [folders, setFolders] = useState<FolderInfo[]>([]), [groups, setGroups] = useState<GroupInfo[]>([]), [group, setGroup] = useState<GroupInfo | null>(null), [people, setPeople] = useState<{ user_id: string; name: string }[]>([]), [docs, setDocs] = useState<DocInfo[]>([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [modal, setModal] = useState<"folder" | "group" | "document" | null>(null), [busy, setBusy] = useState(false), [name, setName] = useState(""), [access, setAccess] = useState("private"), [selectedGroup, setSelectedGroup] = useState(groupId ?? ""), [password, setPassword] = useState(""), [invite, setInvite] = useState("");
  const refresh = useCallback(async () => {
    setLoading(true); setError("");
    try { const current = await api<Session>("/api/session"); setSession(current);
      const fs = await api<{ folders: FolderInfo[] }>("/api/folders"); setFolders(fs.folders);
      if (current.user) { const gs = await api<{ groups: GroupInfo[] }>("/api/groups"); setGroups(gs.groups); if (groupId) { const g = await api<{ group: GroupInfo; members: { user_id: string; name: string }[] }>(`/api/groups?id=${groupId}`); setGroup(g.group); setPeople(g.members); const d = await api<{ documents: DocInfo[] }>(`/api/documents?group=${groupId}`); setDocs(d.documents); } }
    } catch (e) { setError((e as Error).message); } finally { setLoading(false); }
  }, [groupId]);
  useEffect(() => { void refresh(); setInvite(new URLSearchParams(location.search).get("convite") ?? ""); }, [refresh]);
  function open(kind: "folder" | "group" | "document") { setName(""); setPassword(""); setAccess(groupId ? "group" : "private"); setSelectedGroup(groupId ?? ""); setModal(kind); }
  async function create(e: React.FormEvent) { e.preventDefault(); setBusy(true); try { const result = await post<{ id: string }>(modal === "folder" ? "/api/folders" : modal === "group" ? "/api/groups" : "/api/documents", { name, access, password, groupId: selectedGroup || groupId }); setModal(null); if (modal === "document") location.assign(`/documentos/${result.id}`); else { toast.success(modal === "folder" ? "Pasta criada." : "Grupo criado."); await refresh(); } } catch (e) { toast.error((e as Error).message); } finally { setBusy(false); } }
  async function join(e: React.FormEvent) { e.preventDefault(); setBusy(true); try { let code = invite.trim(); if (code.startsWith("https://")) code = new URL(code).searchParams.get("convite") ?? ""; const result = await post<{ id: string }>("/api/groups", { invite: code }); location.assign(`/grupos/${result.id}`); } catch (e) { toast.error((e as Error).message); } finally { setBusy(false); } }
  async function copyInvite() { if (!group?.invite) return; try { await navigator.clipboard.writeText(`${location.origin}/grupos?convite=${group.invite}`); toast.success("Convite copiado. Quem receber poderá entrar no grupo."); } catch { toast.error("Não foi possível copiar. Copie o código exibido abaixo."); } }
  return <main className="main-shell library-shell">{groupId && <a className="back-link" href="/grupos">← Meus grupos</a>}<div className="section-heading"><div><span className="eyebrow">{groupId ? "UM ESPAÇO PARA FAZER JUNTO" : view === "folders" ? "CADA ARQUIVO NO SEU LUGAR" : "COMPARTILHE O TRABALHO"}</span><h1>{groupId ? group?.name ?? "Seu grupo" : view === "folders" ? "Pastas" : "Grupos & documentos"}<span>.</span></h1><p>{groupId ? "Arquivos, documentos e pessoas no mesmo espaço." : view === "folders" ? "Organize seus arquivos e escolha quem pode acessar." : "Crie um grupo, convide pessoas e trabalhem juntos."}</p></div>{session?.user && <Button className="primary-button" onClick={() => open(groupId ? "document" : view === "folders" ? "folder" : "group")}><Plus />{groupId ? "Novo documento" : view === "folders" ? "Nova pasta" : "Novo grupo"}</Button>}</div>
    {session && !session.user && <SignIn path={groupId ? `/grupos/${groupId}` : view === "folders" ? "/pastas" : `/grupos${invite ? `?convite=${encodeURIComponent(invite)}` : ""}`} />}
    {error && <div className="error-box" role="alert"><p>{error}</p><Button variant="outline" onClick={refresh}>Tentar novamente</Button></div>}
    {loading ? <div className="resource-grid"><Skeleton className="h-40" /><Skeleton className="h-40" /></div> : groupId && group ? <>
      <section className="group-members"><div><span className="eyebrow">{people.length} {people.length === 1 ? "PESSOA NO GRUPO" : "PESSOAS NO GRUPO"}</span><div className="member-chips">{people.map(p => <span key={p.user_id}><span className="avatar-letter">{p.name.charAt(0).toUpperCase()}</span>{p.name}</span>)}</div></div><div className="invite-area"><Button variant="outline" onClick={copyInvite}><Link2 />Copiar convite</Button><small>Código: <code>{group.invite}</code></small></div></section>
      <section className="library-section"><div className="files-heading"><h2>Documentos compartilhados</h2><span className="resource-meta">Edição conjunta e tela ao vivo</span></div>{docs.length ? <div className="resource-grid">{docs.map(doc => <a href={`/documentos/${doc.id}`} className="resource-card document-card" key={doc.id}><span className="resource-icon"><FileText /></span><strong>{doc.name}</strong><span className="resource-meta">Atualizado em {new Date(doc.updated_at).toLocaleDateString("pt-BR")}</span><ArrowUpRight className="resource-arrow" size={19} /></a>)}</div> : <Empty className="library-empty"><FileText /><EmptyTitle>Um documento para pensar junto.</EmptyTitle><EmptyDescription>Crie o primeiro documento e todos do grupo poderão editar.</EmptyDescription><Button onClick={() => open("document")} className="primary-button"><Plus />Criar documento</Button></Empty>}</section>
      <section className="library-section"><div className="files-heading"><h2>Pastas do grupo</h2><Button variant="outline" onClick={() => open("folder")}><Plus />Nova pasta</Button></div><FolderGrid folders={folders.filter(f => f.group_id === groupId)} />{!folders.some(f => f.group_id === groupId) && <p className="muted-copy">Nenhuma pasta criada neste grupo.</p>}</section>
    </> : view === "folders" ? folders.length ? <FolderGrid folders={folders} /> : <Empty className="library-empty"><Folder /><EmptyTitle>Suas pastas aparecem aqui.</EmptyTitle><EmptyDescription>Crie uma pasta pública, privada ou compartilhada com um grupo.</EmptyDescription></Empty> : session?.user ? <><form className="join-group" onSubmit={join}><div><strong>Recebeu um convite?</strong><p>Cole o código ou o link para entrar no grupo.</p></div><Input aria-label="Código ou link do convite" value={invite} onChange={e => setInvite(e.target.value)} placeholder="Código ou link do convite" required /><Button disabled={busy} className="primary-button">Entrar no grupo</Button></form>{groups.length ? <div className="resource-grid">{groups.map(g => <a className="resource-card" href={`/grupos/${g.id}`} key={g.id}><span className="resource-icon"><Users /></span><strong>{g.name}</strong><span className="resource-meta">{g.member_count} {g.member_count === 1 ? "pessoa" : "pessoas"}</span><ArrowUpRight className="resource-arrow" size={19} /></a>)}</div> : <Empty className="library-empty"><Users /><EmptyTitle>Trabalhar junto começa aqui.</EmptyTitle><EmptyDescription>Crie um grupo ou entre usando um convite.</EmptyDescription></Empty>}</> : null}
    {session?.admin && <a className="admin-link" href="/moderacao"><ShieldCheck size={17} />Analisar denúncias</a>}
    <Dialog open={Boolean(modal)} onOpenChange={v => !v && setModal(null)}><DialogContent><DialogHeader><DialogTitle>{modal === "folder" ? "Nova pasta" : modal === "group" ? "Novo grupo" : "Novo documento"}</DialogTitle><DialogDescription>{modal === "folder" ? "Escolha quem pode acessar. A senha será exigida também para abrir os arquivos." : modal === "group" ? "Depois de criar, copie o convite para chamar outras pessoas." : "Todos do grupo poderão escrever juntos e compartilhar a tela."}</DialogDescription></DialogHeader><form onSubmit={create} className="form-stack"><label>Nome<Input autoFocus value={name} onChange={e => setName(e.target.value)} maxLength={100} required placeholder={modal === "folder" ? "Ex.: Arquivos do projeto" : modal === "group" ? "Ex.: Equipe de criação" : "Ex.: Ideias para o projeto"} /></label>{modal === "folder" && <><label>Acesso<Select value={access} onValueChange={setAccess}><SelectTrigger className="w-full" aria-label="Acesso da pasta"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="private">Privada — só eu</SelectItem><SelectItem value="public">Pública — qualquer pessoa</SelectItem><SelectItem value="group">Compartilhada com um grupo</SelectItem></SelectContent></Select></label>{access === "group" && <label>Grupo<Select value={selectedGroup} onValueChange={setSelectedGroup}><SelectTrigger className="w-full" aria-label="Grupo da pasta"><SelectValue placeholder="Escolha um grupo" /></SelectTrigger><SelectContent>{groups.map(g => <SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>)}</SelectContent></Select></label>}<label>Senha <span className="optional-label">(opcional)</span><Input type="password" value={password} onChange={e => setPassword(e.target.value)} minLength={6} maxLength={128} autoComplete="new-password" placeholder="Pelo menos 6 caracteres" /></label></>}<Button className="primary-button" disabled={busy || (modal === "folder" && access === "group" && !selectedGroup)}>{busy && <Loader2 className="spin" />}Criar {modal === "folder" ? "pasta" : modal === "group" ? "grupo" : "documento"}</Button></form></DialogContent></Dialog>
  </main>;
}
export function FolderView({ id }: { id: string }) { const [info, setInfo] = useState<FolderInfo | null>(null), [error, setError] = useState(""), [password, setPassword] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(() => api<FolderInfo>(`/api/folders?id=${id}`).then(setInfo).catch(e => setError(e.message)), [id]); useEffect(() => { void load(); }, [load]);
  async function unlock(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { await post(`/api/folders/${id}/unlock`, { password }); setPassword(""); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  if (info && !info.locked) return <FileHub folderId={id} folderName={info.name} canUpload={info.owner || info.access === "group"} />;
  return <main className="main-shell"><a className="back-link" href="/pastas">← Todas as pastas</a>{info?.locked ? <section className="password-card"><span className="resource-icon"><FolderLock /></span><h1>{info.name}</h1><p>Esta pasta está protegida. Informe a senha para acessar seus arquivos.</p><form className="form-stack" onSubmit={unlock}><label>Senha da pasta<Input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} maxLength={128} required /></label><Button className="primary-button" disabled={busy}>{busy && <Loader2 className="spin" />}Abrir pasta</Button></form>{error && <p className="inline-error" role="alert">{error}</p>}</section> : error ? <div className="error-box"><p>{error}</p><SignIn path={`/pastas/${id}`} /></div> : <Skeleton className="h-60 w-full" />}</main>;
}
type ReportInfo = { id: string; file_id: string; name: string; reason: string; details: string; created_at: number };
export function Moderation() { const [reports, setReports] = useState<ReportInfo[]>([]), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const load = useCallback(() => { setLoading(true); api<{ reports: ReportInfo[] }>("/api/reports").then(r => setReports(r.reports)).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []); useEffect(load, [load]);
  async function dismiss(id: string) { try { await api("/api/reports", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); load(); } catch (e) { toast.error((e as Error).message); } }
  return <main className="main-shell library-shell"><div className="section-heading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Denúncias<span>.</span></h1><p>Analise cada denúncia antes de remover um arquivo.</p></div></div>{error ? <div className="error-box"><p>{error}</p><SignIn path="/moderacao" /></div> : loading ? <Skeleton className="h-40" /> : reports.length ? reports.map(r => <article className="report-card" key={r.id}><div><span className="report-reason">{r.reason}</span><h2><a href={`/f/${r.file_id}`}>{r.name}</a></h2><p>{r.details || "Sem detalhes adicionais."}</p><small>{new Date(r.created_at).toLocaleString("pt-BR")}</small></div><div className="report-actions"><Button variant="outline" onClick={() => dismiss(r.id)}>Encerrar denúncia</Button><FileActions file={{ id: r.file_id, name: r.name, canDelete: true, mime: "", size: 0, created_at: 0 }} onDeleted={load} /></div></article>) : <Empty className="library-empty"><ShieldCheck /><EmptyTitle>Nenhuma denúncia pendente.</EmptyTitle><EmptyDescription>As novas denúncias aparecerão aqui.</EmptyDescription></Empty>}</main>;
}
