import { identity, member, requireAccount } from "@/lib/access";
import { ApiError, handle, json, readJson, sameOrigin, storage } from "@/lib/storage";
export async function GET(request: Request) { return handle(async () => { const who = await identity(request); requireAccount(who); const id = new URL(request.url).searchParams.get("id"); const { db } = storage();
  if (id) { await member(id, who); const group = await db.prepare("SELECT * FROM groups WHERE id = ?").bind(id).first(); const people = await db.prepare("SELECT user_id, name FROM members WHERE group_id = ?").bind(id).all(); return json({ group, members: people.results }); }
  const groups = await db.prepare("SELECT g.id, g.name, g.owner_id, g.created_at, (SELECT count(*) FROM members m WHERE m.group_id = g.id) AS member_count FROM groups g JOIN members m ON m.group_id = g.id WHERE m.user_id = ? ORDER BY g.created_at DESC").bind(who.userId).all(); return json({ groups: groups.results });
}); }
export async function POST(request: Request) { return handle(async () => { sameOrigin(request); const who = await identity(request); requireAccount(who); const body = await readJson(request); const { db } = storage();
  if (body?.invite) { if (typeof body.invite !== "string" || body.invite.length > 100) throw new ApiError(400, "Código inválido."); const group = await db.prepare("SELECT id FROM groups WHERE invite = ?").bind(body.invite).first<{ id: string }>(); if (!group) throw new ApiError(404, "Convite não encontrado."); await db.prepare("INSERT INTO members (group_id, user_id, name, joined_at) VALUES (?, ?, ?, ?) ON CONFLICT(group_id, user_id) DO NOTHING").bind(group.id, who.userId, who.name, Date.now()).run(); return json({ id: group.id }); }
  if (typeof body?.name !== "string" || !body.name.trim() || body.name.length > 100) throw new ApiError(400, "Escolha um nome de até 100 caracteres.");
  const id = crypto.randomUUID(), invite = crypto.randomUUID(); await db.batch([db.prepare("INSERT INTO groups (id, name, owner_id, invite, created_at) VALUES (?, ?, ?, ?, ?)").bind(id, body.name.trim(), who.userId, invite, Date.now()), db.prepare("INSERT INTO members (group_id, user_id, name, joined_at) VALUES (?, ?, ?, ?)").bind(id, who.userId, who.name, Date.now())]); return json({ id }, 201);
}); }
